/* ─────────────────────────────────────────────────────────────────
   circles.js
   Circle geometry, colour, and sonic identity for Kandinsky's
   "Circles in a Circle" (1923).  Positions are defined relative
   to an 800 × 800 canvas; the main circle sits at (400, 400) r=375.
   ───────────────────────────────────────────────────────────────── */

const NOTE_FREQ = {
  C3: 130.81, D3: 146.83, E3: 164.81, F3: 174.61,
  G3: 196.00, A3: 220.00, B3: 246.94,
  C4: 261.63, D4: 293.66, E4: 329.63, F4: 349.23,
  G4: 392.00, A4: 440.00, B4: 493.88, C5: 523.25,
};

/* Interactive circles — each maps 1-to-1 with a circle in the painting */
const KANDINSKY_CIRCLES = [
  {
    id: 0,
    name: 'Golden Sun',
    x: 278, y: 248, r: 112,
    color: '#E8B030',
    strokeColor: null,
    note: 'C4', freq: NOTE_FREQ.C4, wave: 'sine',
    overlay: 'color-dodge',
    description: 'Warm gold — the tonic centre, full and resonant',
  },
  {
    id: 1,
    name: 'Deep Night',
    x: 528, y: 308, r: 92,
    color: '#1A2E7C',
    strokeColor: null,
    note: 'G3', freq: NOTE_FREQ.G3, wave: 'triangle',
    overlay: 'multiply',
    description: 'Indigo — low fifth, a gravitational anchor',
  },
  {
    id: 2,
    name: 'Crimson Core',
    x: 348, y: 428, r: 66,
    color: '#C0392B',
    strokeColor: null,
    note: 'E4', freq: NOTE_FREQ.E4, wave: 'sawtooth',
    overlay: 'overlay',
    description: 'Crimson — sharp major third, energetic',
  },
  {
    id: 3,
    name: 'Forest Breath',
    x: 492, y: 512, r: 48,
    color: '#27884A',
    strokeColor: null,
    note: 'A4', freq: NOTE_FREQ.A4, wave: 'sine',
    overlay: 'screen',
    description: 'Lush green — pure sixth, open and clear',
  },
  {
    id: 4,
    name: 'Ivory Dream',
    x: 232, y: 472, r: 56,
    color: '#F0EAD2',
    strokeColor: '#AAAAAA',
    note: 'D4', freq: NOTE_FREQ.D4, wave: 'triangle',
    overlay: 'screen',
    description: 'Ivory — soft second, ethereal and light',
  },
  {
    id: 5,
    name: 'Royal Violet',
    x: 592, y: 192, r: 40,
    color: '#6B2387',
    strokeColor: null,
    note: 'B4', freq: NOTE_FREQ.B4, wave: 'sine',
    overlay: 'color-dodge',
    description: 'Violet — leading tone, mysterious',
  },
  {
    id: 6,
    name: 'Amber Spark',
    x: 418, y: 182, r: 36,
    color: '#E07800',
    strokeColor: null,
    note: 'F4', freq: NOTE_FREQ.F4, wave: 'sawtooth',
    overlay: 'overlay',
    description: 'Amber — dissonant fourth, creates tension',
  },
  {
    id: 7,
    name: 'Rose Whisper',
    x: 294, y: 352, r: 30,
    color: '#E87898',
    strokeColor: null,
    note: 'G4', freq: NOTE_FREQ.G4, wave: 'triangle',
    overlay: 'screen',
    description: 'Soft pink — fifth above, delicate',
  },
  {
    id: 8,
    name: 'Arctic Sky',
    x: 568, y: 438, r: 50,
    color: '#7BB8D4',
    strokeColor: null,
    note: 'A3', freq: NOTE_FREQ.A3, wave: 'sine',
    overlay: 'overlay',
    description: 'Cool blue — low sixth, expansive',
  },
  {
    id: 9,
    name: 'Earth Umber',
    x: 152, y: 318, r: 40,
    color: '#7B4018',
    strokeColor: null,
    note: 'C3', freq: NOTE_FREQ.C3, wave: 'sawtooth',
    overlay: 'multiply',
    description: 'Deep brown — low tonic, grounding',
  },
  {
    id: 10,
    name: 'Scarlet Ring',
    x: 452, y: 578, r: 56,
    color: '#BE2222',
    strokeColor: '#800000',
    note: 'F3', freq: NOTE_FREQ.F3, wave: 'triangle',
    overlay: 'overlay',
    description: 'Scarlet — low fourth, bold and assertive',
  },
  {
    id: 11,
    name: 'Midnight Indigo',
    x: 322, y: 558, r: 34,
    color: '#3D1469',
    strokeColor: null,
    note: 'E3', freq: NOTE_FREQ.E3, wave: 'sine',
    overlay: 'multiply',
    description: 'Deep indigo — low third, introspective',
  },
  {
    id: 12,
    name: 'Lemon Gleam',
    x: 196, y: 158, r: 46,
    color: '#F5E020',
    strokeColor: null,
    note: 'B3', freq: NOTE_FREQ.B3, wave: 'triangle',
    overlay: 'screen',
    description: 'Bright lemon — leading tone below, vivid',
  },
  {
    id: 13,
    name: 'Emerald Point',
    x: 592, y: 528, r: 26,
    color: '#1E8C40',
    strokeColor: null,
    note: 'D3', freq: NOTE_FREQ.D3, wave: 'sine',
    overlay: 'overlay',
    description: 'Emerald — low second, quiet and precise',
  },
  {
    id: 14,
    name: 'Vermilion Dot',
    x: 626, y: 294, r: 24,
    color: '#FF4500',
    strokeColor: null,
    note: 'C5', freq: NOTE_FREQ.C5, wave: 'sawtooth',
    overlay: 'color-dodge',
    description: 'Vermilion — high octave, brilliant accent',
  },
];

/* Non-interactive decorative circles that complete the composition */
const DECORATIVE_CIRCLES = [
  { x: 382, y: 282, r: 16, color: '#2C3E9A', alpha: 0.55 },
  { x: 472, y: 378, r: 12, color: '#E74C3C', alpha: 0.50 },
  { x: 208, y: 392, r: 18, color: '#8E44AD', alpha: 0.50 },
  { x: 542, y: 168, r: 14, color: '#F39C12', alpha: 0.55 },
  { x: 622, y: 432, r: 11, color: '#16A085', alpha: 0.50 },
  { x: 388, y: 492, r:  9, color: '#2C3E50', alpha: 0.45 },
  { x: 168, y: 468, r: 13, color: '#D35400', alpha: 0.45 },
  { x: 508, y: 248, r: 10, color: '#C0392B', alpha: 0.40 },
];
